### ISSUE TITLE
Courier doesn't deliver items when "lock combining" is turned on.

### ISSUE THREAD

**Issue by Krev5** [jeffhill/Dota2#1185]
### Description

Idk, if it is intentional, but sometimes items need to be locked so they would be combined into the correct item and they do not get delivered

**Comment by yckmm** [comment]
Yes, this is intended, it was added in patch [7.23c](https://dota2.fandom.com/wiki/Version_7.23c)

**Comment by xorox11** [comment]
> Yes, this is intended, it was added in patch [7.23c](https://dota2.fandom.com/wiki/Version_7.23c)

The reason why they added that was they allowed couriers to use items so they dont transfer items you want to use from courier. There is no reason to keep it this way anymore.

**Comment by deanrih** [comment]
> > Yes, this is intended, it was added in patch [7.23c](https://dota2.fandom.com/wiki/Version_7.23c)
> 
> The reason why they added that was they allowed couriers to use items so they dont transfer items you want to use from courier. There is no reason to keep it this way anymore.

I beg to differ, there is some scenario when you want to send an item but when your inventory is almost full and/or only want to accept a certain item instead of everything, locking the item is the easier way without manually fiddling and micro-macroing the courier. But I guess looking at the vote means I'm in the minority.
