### ISSUE TITLE
Odd Clip Recorder Behavior

### ISSUE THREAD

**Issue by loegare** [jeffhill/Dota2#1225]
### Description

Tried using the create a clip feature to post here about a different issue and it saved as a .wav file and 795 .jpeg files.

M1 Pro Macbook Pro

### Screenshots

<img width="747" alt="image" src="https://user-images.githubusercontent.com/8977289/173585139-df581232-fba3-43cd-9ecb-d31bf85a602e.png">

<img width="753" alt="image" src="https://user-images.githubusercontent.com/8977289/173585218-126474d3-e5d1-4b7c-9071-1df0f1fa06e0.png">

**Comment by Soong45** [comment]
This is expected behaviour. In the full [battle report update  ](https://www.dota2.com/battlereport), it says the following:
Premium Quality
You can choose advanced rendering features for higher-quality shadows and reflections, hidden in-game UI for the duration of the clip, and smooth framerates up to 90fps. **The tool directly encodes to h.264 video on Windows, and other platforms output individual frames.**

**Comment by loegare** [comment]
> 

oh, thats super weird, missed that somehow, ty
