### ISSUE TITLE
Too small cooldown on tusk's ultimate

### ISSUE THREAD

**Issue by isergeich22** [jeffhill/Dota2#1408]
You create so strong ultimate, which kill any hero with 800 or less health bar, but give this skill soo small cooldown, 20 sec on 1 lvl, 15 on 2 lvl and 10 on 3 lvl, pls check replay of this match and think about what you doing with this so cool game and how that type of patchs break dota 2, with this type of patchs you lose all community very soon, check tusk ultimate and change it pls, we tell you about balance in game about 7-10 years, do the balanced game, if hero have so strong ulti give him 3 or more minutes cooldown

Match ID:6624505933

**Comment by Krev5** [comment]
1. its 1 hit of physical damage. therefore it can be greatly reduced by armour or get immunity by getting ghost for example.
2. its a point-blank-melee-attack
3. if tuskar is a support and doesnt have items, the damage is not going to be significant because the critical hit is based on tusk's damage.
4. it is a 1.3kmmr game. people at this mmr dont know what they should be doing how or when, the cannot farm well either. if one person on any core position is understanding game to a higher extent, they will have no problems dominating the game 1x5.

**Comment by github-is-stupid** [comment]
Not a bug, please close
