### ISSUE TITLE
[Magnus - Visual Bug] - Shockwave Aghanim's scepter armor reduction does not correctly show reduced armor

### ISSUE THREAD

**Issue by kjoudah** [jeffhill/Dota2#1411]
### Ability name

Shockwave

### Description

When Aghanim's scepter is is equipped, shockwave should reduce 75% of the target's armor according to 7.31d. However, after testing it in demo, it does not seem like it reduces 75%. 

Attached is a demo:

Morphling has 60 armor. After being hit by shockwave, he should lose 45 armor. Instead, he only loses 35 armor. 

I tried this in a normal game, and I got the same results

https://user-images.githubusercontent.com/37226235/174460514-cf465c79-24fc-4ada-9fb4-6136ea31ac40.mp4

## EDIT:

According to TheUnholyWrath, the armor is correctly applied. However, the UI does not accurately reflect the armor applied

### Example Match ID (and possibly Timestamp)

This was reproduced in demo

**Comment by TheUnholyWrath** [comment]
Because the armor reduction diminishes over time it actually takes so much time to count up to -45 that it doesn't get all the way there. You can see it is working correctly by hovering over morphlings stats as the shockwave hits, the number is significantly higher than what you see here. 

![20220612131435_1](https://user-images.githubusercontent.com/46859977/174631035-9f828a51-526b-49d9-b958-de50fcfe5978.jpg)

**Comment by kjoudah** [comment]
Okay, even if the armor is correctly reduced, it is still a visual bug.
