### ISSUE TITLE
The Lightning Orchid of Eminent Revival

### ISSUE THREAD

**Issue by Kaori20** [jeffhill/Dota2#1490]
### Cosmetic Item Name

The Lightning Orchid of Eminent Revival style 2 (expectional)

### Description

the hat has lost all its particles and become dull green in colour  plus the fire on the top of the hat has turned into default blue instead of green
### Example Match ID

none 

### Screenshots

what it looks like right now

![image](https://user-images.githubusercontent.com/62170962/174949210-57ef020c-5911-4b75-805a-cac1d1871ae2.png)

 
 what it should like like 
 
![image](https://user-images.githubusercontent.com/62170962/174948439-fa71653e-8c53-4d70-ba29-df943aa520df.png)

**Comment by Kaori20** [comment]
> Great screenshots! Please edit your title for clarity so that it's easier for others to upvote.



> 

thanks, fixed :)

**Comment by Astiberon** [comment]
Please close the post.
This is a mistake on your part.
The effects have not disappeared.
You most likely changed heroes in demo mode a lot of times, because of this, effects often disappear.
Or you used the ultimate effect on another hat.
Here's how to fix it:
-Remove the immortal
-Set default ability effect
- Put on the immortal again
![image](https://user-images.githubusercontent.com/107125193/175012511-13ee372d-7d86-473c-b047-67454af8643c.png)

**Comment by Kaori20** [comment]
> Kaori20

thanks
