### ISSUE TITLE
Dark Seer and LC turns around if you double click Surge and Press the Attack when you have aoe talent

### ISSUE THREAD

**Issue by LokeLok** [jeffhill/Dota2#22]
https://streamable.com/48tihy

**Comment by WingDota** [comment]
The same thing happens when you cast Storm Spirit's ult on the portrait. Which you used to be able to do without turning around

**Comment by Bu3nyy** [comment]
Easiest way to fix these is to allow these abilities to target self or the ground (similar to Earthshaker's Scepter upgrade). This way, double-tap will always use current location.

Warlock's Shadow Word is also affected.

**Comment by jeffhill** [comment]
This will be fixed in the next hotfix, likely tomorrow (it missed the build for the hotfix that went live just this minute). Dark Seer Surge with AoE, LC Press the Attack with AoE, Storm Spirit's Ball Lightning and Warlock's Shadow Word with AoE all reproed the problem and were all fixed with this change. Thanks for the bug report!

**Comment by AmanovAkbar** [comment]
@jeffhill The same issue happens with Treant Protector living armour and probably with every self-castable spell that is originally target and becomes AOE due to a talent/shard/aghanim
