### ISSUE TITLE
"Right click to Force Attack" for ranged heroes causes hero to stop moving when right clicking friendly unit

### ISSUE THREAD

**Issue by Stickerpants** [jeffhill/Dota2#238]
### Description

# Description

When the setting to allow denies via right click (instead of attack command) is enabled, melee heroes retain their original behavior when right clicking on a friendly unit that cannot be denied, and will walk towards the unit.

Unintuitively, ranged heroes will instead turn and face the clicked unit and stand still. This mismatch in behavior depending on hero attack type is confusing for new players, and can often cause them to misplay in situations where they're trying to run away and accidently click on a friendly unit instead of the ground.

It's my opinion that this behavior should be made consistent across the two hero types, and ranged heroes with force attack enabled should also walk towards the clicked friendly unit, which preserves the behavior when force attack is disabled, and makes it consistent with how melee heroes behave regardless of force attack setting.

**ADDENDUM 1:** To clarify some confusion raised in the comments, I'm referring to right clicks issued on friendly units that have high HP and are not valid targets to deny. To be absolutely clear, ranged heroes _should_ still attack deniable units as they currently do, but right clicks on non-deniable units should be a move command in the same way it works for melee heroes.

Please see the attached video for a demonstration of this issue. Thank you!

### Screenshots

https://user-images.githubusercontent.com/2053862/171743914-23866b4f-6118-47da-897a-c3f9f952b36d.mp4

**Comment by AzimsTech** [comment]
It also happens on wards if your hero is close enough.

**Comment by gohyuchen** [comment]
i have used 'right click to force attack' setting for the last 8 years and never even noticed this behavior or had a problem with it. 
it seems like consistent behavior that when you click on the friendly unit, both the melee/range will attempt to make an attack from wherever they are. which is why the melee hero has to move but the ranged hero does not, as long as the target is within range?

**Comment by akshayyalpi97** [comment]
Yes. This happened to me a lot initally. During team fights, I misclicked on an ally and my hero just stopped running. Hopefully something gets done about this.

**Comment by Chrompower** [comment]
This is a VERY annoying bug. When you try to run away from enemys and a teammate is on the way you constantly stop moving because of that.

**Comment by Aphotic** [comment]
yes, I've had this issue many times.

but with your suggestion, a ranged hero should walk to melee range before starting to deny a friendly?

 a workaround can be if the creep is in deny range then hero can stop & attack in place if not then walk towards that creep or bypass/ignore the friendly right-click in general.

the most annoying part of this interaction is with friendly wards IMO.

**Comment by silverm6** [comment]
Somebody pointed out this would screw up right clicking on creeps to deny them since your ranged hero would walk up to them.
Proposal:
new behaviour would apply only when rclicking heroes, couriers, wards. (ranged hero walks up to them as close as possible instead of stopping when in atk range)

**Comment by Cymen90** [comment]
That is the intended behavior. It is called "Force Attack" for that reason, not "right click denies". The units will move into attack range and (if in deny range) attack the friendly unit. Of course melee and ranged heroes will follow the first step differently.

**Comment by silverm6** [comment]
And its used 100% for right click denies so your pedantry is meaningless

**Comment by Stickerpants** [comment]
I've added the following text to address concerns raised by @Aphotic and @silverm6, thank you for input!

> **ADDENDUM 1:** To clarify some confusion raised in the comments, I'm referring to right clicks issued on friendly units that have high HP and are not valid targets to deny. To be absolutely clear, ranged heroes _should_ still attack deniable units, but right clicks on non-deniable units should be a move command, as it is for melee heroes.

**Comment by Aluerie** [comment]
I just want to mention that it doesn't mimic Move command for melee heroes. 

For both ranged and melee this setting mimics A-key press which in fact makes heroes walk into attack range (no matter ally/enemy/possibility to attack) and then attack them if possible. Thus melee heroes come into melee range while ranged stop at their attack range. Move command doesn't behave this way (Move also makes heroes follow the target). 

So there is really *no inconsistency/no bugs* in the way the setting is implemented. 

I'm just afraid that if solution to your QoL suggestion is to change Attack order behavior itself (because this is all this setting does - makes attack order on right-clicking units) then it would be kinda unacceptable for players who don't use the setting. 

However I can admit, with RepeatRightClick and ForceAttack on right click settings on - I often hover over random wards and my allied creeps and thus my hero stops randomly - but it's my fault for not being precise with snapping the mouse all over the screen, however it would be a nice QoL.

**Comment by Stickerpants** [comment]
@Aluerie I can understand your interpretation of how there may not be a "bug" in the strict definition of the word here.

However, the fact remains that this behaviour is frustrating and impacts the gameplay of many players, and is something that should be addressed. All I want is for the issue raised to be fixed, I don't really care about the semantics.

**Comment by silverm6** [comment]
If the change for creeps is controversial, 
at the minimum fixed behaviour should apply when rclicking heroes, couriers, wards. (ranged hero walks up to them as close as possible instead of stopping when in atk range). 
I think that's the most common annoyance with random stopping when right clicking to move.

**Comment by jeffhill** [comment]
I don't play with this option on so I dug around in the code a bit and played around with the feature. @Aluerie is correct, this option was just issuing an A-click when right clicking on allies in almost all cases, but not on friendly wards to avoid giving away their position. In the friendly ward case it was a issuing a move order.

I **think** this solution works for everyone?
- No behavior changes in **any way at all**, unless you have the "Right-Click to Force Attack" option on. No server code changed at all here and it's a one-line change to how orders are issued on the client.
- If you do have the option on, and you right click on an allied unit that is not deemed deniable on your client, it issues a move order to that unit instead (as it current does when you right click a friendly ward).

With the caveat that I don't normally play this way, this subjectively felt better to me between both melee and ranged heroes.

The only loss in functionality I can see here is if you're very far away from the unit, or have very high ping, and you right click on a unit when it's not deniable yet on your client. In the previous system, so long as the unit was deniable when the actual attack swing was started on the server (so *after* moving into range), you'd try to deny. Now, if you right click with this option and your hero moves into range, and during that time the target *becomes* deniable, you'll still move to them (since you issued a move command at the time you clicked), rather than try to deny them. You can fix this by just right-clicking on the target once again - something Dota players tend to do repeatedly anyhow.

Of course an A-click will still issue an attack order in all these cases with behavior exactly as it is today, so nobody's truly losing anything, it's only that this right-click option now behaves very slightly differently when the target's health is on the boundary of becoming deniable (but is not yet deniable), and more consistently when the target is not deniable between ranged and melee heroes. Hopefully this essay makes sense, it's a very long explanation for a fix that in C++ is 34 characters - "|| !IsDeniable( pControlledUnit ) ".

I don't think this change will make the update shipping later today, but it will ship in the next hotfix (most likely tomorrow), so long as nobody finds it disagreeable before then.

**Comment by Stickerpants** [comment]
Thank you for taking the time to look into this @jeffhill, it's very much appreciated 😸

**Comment by Chrompower** [comment]
I think it's a very good solution, excited to test it out. Thank you!

**Comment by ZzZombo** [comment]
This is not how this tracker should function. This is not a small change and it does completely change the way the affected part of the game plays out for me and others. Please revert this change ASAP.

**Comment by Chrompower** [comment]
So basically what you are saying is that you don't want this change because it changes something. 
What is your point @ZzZombo?

**Comment by jeffhill** [comment]
Update: The new behavior will now be an option in the settings for those who'd like it, as of the hotfix later today. @Aluerie you were completely correct about this change being problematic for folks who currently use the option, thank you for trying to warn me.

**Comment by opomuc** [comment]
@jeffhill one problem with the update -- it set default to "To follow". I had "Right-click to force attack" option before and was kinda buffled to find that I can't deny creeps... Had to pause and look through options frantically.

I guess a better way would have been to set "To attack" if one had "Right-click to force attack" enabled, and "To follow" otherwise.

**Comment by ImKMan** [comment]
> i have used 'right click to force attack' setting for the last 8 years and never even noticed this behavior or had a problem with it. 
I have had this problem ALOT, sometimes it causes me to die, especially trying to run away from foes for example, i get stuck in 1 spot and turn around in circles

**Comment by Chrompower** [comment]
Is it maybe possible to adjust the "To Deny" option so that you wake up an ally from Banes nightmare ability with a plain right-click? At the moment you have to a-click your ally to remove / swap nightmare if you have the "To Deny" option selected.
