### ISSUE TITLE
Morphling Hotkeys Bugged

### ISSUE THREAD

**Issue by jeffhill** [jeffhill/Dota2#3]
When Morphling transforms into some heroes (notably Spirit Breaker), his ability hotkeys are incorrect.

**Comment by Anomaluna** [comment]
Also Puck.

**Comment by sidechaincompression** [comment]
Undying as well. The button for tombstone is W as opposed to E.

**Comment by ihxme** [comment]
If copying Invoker, the skills will be Q and E instead of D and F, making it less convenient

**Comment by pibban** [comment]
My hotkeys: Q, W, E, D, F, R 

Heres what I could find.

Wisp: "Overcharge" is bound to F, instead of E
Elder Titan: "Move Astral Spirit" has no hotkey at all. As Elder Titan, it's bound to D
Timbersaw: "Flamethrower" is bound to D, instead of F
Faceless Void: If Void has shard, "Time Dilation" is bound to E instead of W, "Reverse Time Walk" is bound to W, instead of D
Spectre: "Shadowstep "is bound to D, instead of F, "Reality" is bound to F, instead of D

**Comment by jeffhill** [comment]
This will be fixed in the next hotfix, most likely later today. Thank you for all the detailed repro cases, it was helpful to confirm that the fix caught them all!

**Comment by gohyuchen** [comment]
hey man thanks for working on this. time for me to 'forget' that undy and bara skills are swapped when morphed...haha! especially since they are usually great targets for morph
