### ISSUE TITLE
QOL: Underlord's Fiend Gate should display countdown to Expiration (visible to at least friendly heroes)

### ISSUE THREAD

**Issue by Big-Mudd** [jeffhill/Dota2#47]
It is currently very difficult to assess when the Fiend's Gate will disappear after it is cast which may cause heroes to become stranded on the other side. There should be a countdown displayed over the gate similar to Jingu Mastery or Curse of Avernus numbers on affected heroes. Whether this countdown should be visible to the enemy team is up for debate.

**Comment by anonymo0se** [comment]
I think it should also have a selfcast (double tap) behaviour. Maybe selfcast should make the hero face their fountain (just like TP selfcast does) and cast a fiend's gate right at the fountain's entrance (because you cannot cast it inside the fountain).

![image](https://user-images.githubusercontent.com/53087065/171794797-1d134f79-7b80-4adc-9fc2-c479b5a389c1.png)

**Comment by jeffhill** [comment]
The countdown timer will ship in the June 8th update. I've just borrowed the Wisp relocate timer for now, but it's possible one of the talented particle artists will have time to tinker with it before it ships. The timer is only visible to teammates and spectators, not enemies. Thank your for the request!

The double-tap cast sounds like a fine QoL feature, but a different thing from the main issue. Please submit it as another issue. Sorry to be kind of a jerk about this, but it's early days in this experiment and it's important to figure out how to make the bug tracker thing work fairly and correctly.
