### ISSUE TITLE
Arc Warden - Basher never procs for clone

### ISSUE THREAD

**Issue by jrenner** [jeffhill/Dota2#48]

**Comment by Yan00r** [comment]
Ahah it's isn't bug. This is how game should work

**Comment by Daar543** [comment]
Since the only "clone" hero is Monkey King, for whom disabling Skull Basher is logical (can get permastunned in the circle), it is possible that this could be also done to Arc Warden accidentally.

I do not see "game balance" issue here, as the clone is ranged, has generally low bash chance, and the item is not very strong on the original hero

**Comment by MrMooEar** [comment]
Tempest Doubles are specifically coded to not proc Basher.

**Comment by TheZett** [comment]
> Tempest Doubles are specifically coded to not proc Basher.

It is the other way around.

Basher is hardcoded to not proc at all when carried by a unit that has "isClone true" as its property.

While this was not in any changelog, it is 'intended' as of the last spring cleaning update, which mentions that basher does not work for Tempest Doubles (prior to that it was only intended for MK clones).

**Comment by duckbotx** [comment]
<img width="316" alt="image" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/79627584/c365c493-87df-4eff-9652-28c423ccd48a">

**Comment by cageoldcss** [comment]
2026... FIX PLEASE! VALVE
