### ISSUE TITLE
ability description is wrong

### ISSUE THREAD

**Issue by malicethegod** [jeffhill/Dota2#575]
### Hero and spell

tusk 

### Description

when using octarine core and spell prism in the description of the first skill shows cd 9.2 but in fact there is 6.0

### Screenshots

![image](https://user-images.githubusercontent.com/106849292/172026873-9ef9c812-8c52-4d0c-b593-dc12c0dd63d2.png)
![image](https://user-images.githubusercontent.com/106849292/172026897-bc9f2efe-0636-464a-a7b8-eef48654b2b5.png)

**Comment by hydrazines** [comment]
Note for repro: -6s Ice Shards CD talent must also be selected.

**Comment by LokeLok** [comment]
I found one more after checking all the cooldown talents in the game. Sven's 15 talent(right) has the same issue. Note: I didn't check the talents that lower charge restore time. Since charge based abilities doesn't update their cooldown at all. 

Video of Tusk and Sven: https://streamable.com/julg7w
